
  function cacheElements() {
    const ids = [
      'current-date-label', 'today-entry-date', 'today-dose', 'today-time', 'today-status-heading', 'today-status-badge',
      'today-profile-switcher', 'all-profiles-dashboard', 'all-profiles-progress', 'all-profiles-list', 'single-profile-dashboard',
      'today-profile-avatar', 'main-action-eyebrow', 'main-profile-name', 'main-status-badge',
      'main-place-value', 'main-dose-value', 'main-time-value', 'main-ampoule-value', 'main-dose-number-value', 'main-remaining-ml-value', 'main-doses-left-value', 'main-ampoule-open-value',
      'main-action-heading', 'main-action-text', 'recommended-save-button', 'recommended-edit-button', 'recommended-skip-button', 'recommended-manual-button',
      'ampoule-start-main-button', 'ampoule-alert', 'ampoule-alert-title', 'ampoule-alert-text',
      'today-dose-decrease', 'today-dose-increase', 'today-undo-button', 'today-confirmation',
      'today-reminder-title', 'today-reminder-text', 'today-reminder-button', 'today-details',
      'voice-button', 'voice-help', 'voice-result', 'voice-result-text', 'selected-place', 'save-button', 'save-help',
      'skip-button', 'last-place', 'suggested-place', 'ampoule-status', 'use-suggestion-button', 'mini-calendar', 'recent-list',
      'date-chip', 'dose-chip', 'time-chip', 'place-field', 'entry-dialog', 'entry-form',
      'entry-dialog-title', 'entry-id', 'entry-date', 'entry-time', 'entry-dose', 'entry-unit', 'entry-side',
      'entry-site', 'entry-status', 'entry-note', 'delete-entry-button', 'dialog-close-button',
      'dialog-cancel-button', 'toast-region', 'live-region', 'calendar-prev', 'calendar-next', 'calendar-today-button',
      'calendar-month-label', 'calendar-month-summary', 'calendar-grid', 'calendar-profile-filter', 'calendar-scope-label', 'calendar-profile-legend', 'selected-day-label', 'selected-day-entries',
      'add-for-selected-day', 'history-profile-filter', 'history-scope-label', 'history-search', 'status-filter', 'site-filter', 'history-correction-filter', 'history-clear-filters', 'history-list',
      'history-empty', 'settings-dose', 'settings-unit', 'settings-time', 'settings-dose-effective-date', 'settings-dose-change-note', 'ampoule-start-date',
      'ampoule-start-number', 'ampoule-volume', 'ampoule-dose-ml', 'ampoule-max-open-days', 'ampoule-start-today-button', 'ampoule-new-button',
      'ampoule-management-summary', 'ampoule-list', 'voice-feedback-toggle',
      'voice-confirm-toggle', 'save-voice-settings-button', 'save-settings-button', 'reminder-enabled-toggle', 'reminder-time',
      'save-reminder-button', 'notification-permission-status', 'request-notification-button',
      'test-notification-button', 'reminder-diagnostics-overall', 'reminder-diagnostic-permission',
      'reminder-diagnostic-channel', 'reminder-diagnostic-exact-alarm', 'reminder-diagnostic-next',
      'reminder-diagnostics-note', 'reminder-diagnostics-checked', 'refresh-reminder-diagnostics-button',
      'open-notification-settings-button', 'request-exact-alarm-button',
      'report-profile-filter', 'report-date-from', 'report-date-to', 'report-include-ampoules', 'report-scope-summary', 'report-preview-button', 'export-report-button', 'backup-panel-button',
      'report-preview-dialog', 'report-preview-close-button', 'report-preview-frame', 'report-print-button',
      'export-report-dialog', 'export-report-close-button', 'backup-dialog', 'backup-close-button',
      'export-pdf-button', 'export-word-button', 'export-json-button', 'export-profile-json-button', 'export-csv-button', 'import-button',
      'restore-auto-backup-button', 'auto-backup-summary', 'import-preview', 'import-preview-summary', 'import-preview-profiles',
      'import-preview-warning', 'import-confirm-button', 'import-cancel-button',
      'backup-password', 'backup-password-confirm', 'import-file', 'clear-data-button', 'data-backup-section', 'header-install-button',
      'desktop-install-button', 'settings-install-button', 'version-label', 'permissions-dialog',
      'pwa-install-dialog', 'pwa-install-dialog-note', 'pwa-install-confirm-button', 'pwa-install-later-button',
      'permission-microphone-button', 'permission-notification-button', 'permission-storage-button',
      'permission-microphone-status', 'permission-notification-status', 'permission-storage-status',
      'permissions-finish-button', 'permissions-skip-button', 'microphone-permission-settings', 'notification-permission-settings',
      'storage-permission-settings', 'open-permissions-button', 'place-picker-dialog', 'place-picker-options', 'place-picker-edit-button', 'place-picker-close-button',
      'active-profile-button', 'active-profile-avatar', 'active-profile-name', 'profiles-summary', 'manage-profiles-button',
      'profiles-dialog', 'profiles-dialog-close-button', 'profiles-list', 'add-profile-button',
      'profile-editor-dialog', 'profile-editor-form', 'profile-editor-title', 'profile-editor-id', 'profile-name-input',
      'profile-icon-options', 'profile-color-options', 'profile-editor-cancel-button', 'profile-editor-close-button',
      'profile-delete-dialog', 'profile-delete-close-button', 'profile-delete-cancel-button', 'profile-delete-confirm-button',
      'profile-delete-name', 'profile-delete-input', 'profile-delete-warning',
      'settings-profile-context', 'settings-profile-avatar', 'settings-profile-name', 'settings-profile-note',
      'profile-health-name', 'profile-health-avatar', 'profile-current-dose', 'profile-latest-height', 'profile-latest-weight', 'profile-regularity-rate',
      'profile-open-treatment-button', 'profile-medical-form', 'profile-birth-date', 'profile-doctor-name', 'profile-clinic-name', 'profile-medication-name', 'profile-diagnosis', 'profile-medical-notes',
      'profile-regularity-summary', 'profile-regularity-chart', 'profile-regularity-details',
      'profile-measurement-form', 'profile-measurement-date', 'profile-height-cm', 'profile-weight-kg', 'profile-measurement-note', 'profile-measurement-list',
      'profile-dose-history-form', 'profile-dose-history-date', 'profile-dose-history-value', 'profile-dose-history-unit', 'profile-dose-history-note', 'profile-dose-history-list',
      'profile-ampoules-opened', 'profile-ampoules-finished', 'profile-ampoules-used', 'profile-ampoule-active-remaining', 'profile-ampoule-stats-note',
      'profile-doctor-report-button', 'profile-doctor-export-button',
      'injection-order-summary', 'injection-order-list', 'injection-order-side', 'injection-order-site',
      'injection-order-add-button', 'injection-order-reset-button', 'injection-order-warning',
      'settings-layout', 'settings-category-list', 'settings-section-back-button', 'settings-panels', 'save-ampoule-settings-button',
      'security-storage-status', 'security-pin-status', 'security-pin-form', 'security-current-pin-wrap',
      'security-current-pin', 'security-new-pin', 'security-confirm-pin', 'security-pin-submit-button',
      'security-remove-pin-button', 'security-biometric-status', 'security-biometric-button', 'security-auto-lock',
      'security-lock-now-button', 'security-startup-cover', 'security-startup-message', 'security-privacy-cover',
      'security-lock-screen', 'security-unlock-form', 'security-unlock-pin', 'security-unlock-message',
      'security-unlock-error', 'security-unlock-biometric', 'check-update-button', 'download-update-button',
      'update-status', 'settings-version-label', 'pwa-maintenance-controls', 'pwa-worker-status',
      'pwa-cache-status', 'pwa-online-status', 'pwa-install-status', 'refresh-pwa-resources-button',
      'apply-pwa-update-button', 'theme-mode-control', 'theme-system',
      'theme-light', 'theme-dark', 'theme-status'
    ];
    ids.forEach((id) => { el[id] = document.getElementById(id); });
  }
